### ISSUE TITLE
Rename to Vogue?

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/vogue#1]
Are we going to rename this one to Vogue or are we creating a new repo? @hassanfa

**Comment by hassanfa** [comment]
Instead of forking from your repo, I would rename this one to Vogue (there is no other trending related repo). @ingkebil Do we have any other trending related repo? cause I couldn't find one.

**Comment by ingkebil** [comment]
Nope. This is the one :)

**Comment by hassanfa** [comment]
👍 
It seems I don't have permission to do so. Would you mind changing it for us? Or transferring the ownership to Maya or me?

**Comment by ingkebil** [comment]
You're both admins of this repo now. Have fun! :)

**Comment by ingkebil** [comment]
Meaning: you are setting the policies on how you are coding and putting code into this repo.
