### ISSUE TITLE
Sequence Type over time plot 

### ISSUE THREAD

**Issue by sylvinite** [Clinical-Genomics/vogue#108]
## General Plot information
**Describe the plot shortly in words:**
Plot aims to describe the prevalence of sequence type as a function of time.
**Plot title:**
Sequence Type over time
**Plot type:** (scatter, bar...)
"Spline", selectable organism for each plot (dropdown).
**Plot cathegory:** (Microbial Prep, Cancer QC...)
Sequence Type (Microbial) [ST8, ST100, ...]

## X-axis
**Source:** (Lims\*, StatusDB...)
Date received (LIMS)
**Unit:** (hours, concentration (nM)...)
From month to quarter, depends on how data looks
**Calculations:** (Need to perform any calculations on the 'raw data'?)

## Y-axis
**Source:** (Lims\*, StatusDB...)
 Trending database, micro, (subcategory 'blast_pubmlst : 'sequence_type')
**Unit:** (Hours, Concentration (nM)...)
Count
**Calculations:** (Need to perform any calculations on the 'raw data'?)

## Group by 
**Group by:** (lot number, sample material, application tag...)
Sequence Type
**Source:** (Lims\*,StatusDB...)

\* If source is LIMS: specify Protocol, Step and Field if applicable.

**Comment by hassanfa** [comment]
@mayabrandi Now that we have MicroSalt in Vogue, could you check this one as well?

**Comment by mayabrandi** [comment]
@talnor är denna fortfarande nåt ni vill ha? Jag har för mig jag hade bygt en sån men att vi tog bort den.. Ska vi arkivera?

**Comment by talnor** [comment]
@mayabrandi Yes, den här bestämde vi oss för att skippa. Det går bra att arkivera.
