### ISSUE TITLE
QC metrics over time plot

### ISSUE THREAD

**Issue by sylvinite** [Clinical-Genomics/vogue#109]
## General Plot information
**Describe the plot shortly in words:**
**Plot title:** QC metrics over time
**Plot type:** (scatter, bar...)
"Spline"
**Plot cathegory:** (Microbial Prep, Cancer QC...)
Microbial QC

## X-axis
**Source:** (Lims\*, StatusDB...)
Lims received date
**Unit:** (hours, concentration (nM)...)
Months
**Calculations:** (Need to perform any calculations on the 'raw data'?)

## Y-axi
**Source:** (Lims\*, StatusDB...)
['picard_markduplicate'] = {'insert_size', 'duplication_rate'}
['microsalt_samtools_stats'] = {'total_reads', 'mapped_rate', 'average_coverage', 
                                                            'coverage_10x', 'coverage_30x', 'coverage_50x', 'coverage_100x'}
**Unit:** (Hours, Concentration (nM)...)
Count
**Calculations:** (Need to perform any calculations on the 'raw data'?)

## Group by 
**Group by:** (lot number, sample material, application tag...)
alla fyra %baspar över coverage Y X i samma plot . övriga i egna. 
Drop down
**Source:** (Lims\*,StatusDB...)

\* If source is LIMS: specify Protocol, Step and Field if applicable.

**Comment by hassanfa** [comment]
@mayabrandi Apologies for tagging you multiple times, could you have a look at this as well?
