### ISSUE TITLE
vogue --version returns vogue's version

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/vogue#147]
**Who: Does your feature request involves multiple parties?**
Involves TTN.

**Scope**
CLI.

**Please describe the problem that this feature request can solve.**
Now the `vogue --version` returns versions from software involved in the package but not the one of vogue itself:

```
(S_vogue) [hiseq.clinical@hippocampus ~]$ vogue --version
Python 3.6.0
Flask 1.1.1
Werkzeug 0.16.0
```

**Describe the solution you'd like**
```
(S_vogue) [hiseq.clinical@hippocampus ~]$ vogue --version
vogue, version 0.2.0
```

### Optional:
**Describe alternatives you've considered**
Now the update script is getting the version by parsing the PKG.NFO from the installed package: `${CONDA_PREFIX}/lib/python*/site-packages/vogue-*-py*.egg-info/PKG-INFO`. Which works as long as you stick to installing through the update script ;)

**Additional context**

**Comment by hassanfa** [comment]
Well, that's not how it should be. I'm looking into it.
