### ISSUE TITLE
reagent label data for EX and PA

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/vogue#172]
load reagent_labels only pick up data from sampled that were passed as single samples into the Define step. This means we miss samples that we pool in the twist wf. Typically with app tags beginning with EX and PA. The fraction of pool can be fetched from earlier in the workflow. From the step called: "Pool Samples TWIST 1"

1) go back in history to the step
2) from the output artifact (the pool), get udf: "Total amount (ng)"
3) from the input artifact (sample in pool), get udfs: Volume and Concentration
4) calculate fraction of pool = Vol*Concentration/(Total amount)
5) in the define step, calculate the nr of reads: fraction*reads_to_sequence.

**Comment by hassanfa** [comment]
Is this still relevant @mayabrandi

**Comment by mayabrandi** [comment]
No longer relavant
