### ISSUE TITLE
Docker-compose

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/vogue#201]
Wishlists:
1. communicate with a remote MongoDB through container
1. Docker compose definition to make deployment easier
1. Should work either via `gunicorn --bind="some_host:a_port" vogue.server.auto:app` or `vogue run -h some_host -p some_port`. Which one's better?

**Comment by hassanfa** [comment]
This is a quite easy fix. I'll be fixing it later this week.

**Comment by moonso** [comment]
I struggled with this for a while, you can have a look at the solution that worked for med [here](https://github.com/Clinical-Genomics/loqusdbapi). There are some nice containers for running flask/gunicorn apps [here](https://github.com/tiangolo/meinheld-gunicorn-flask-docker) if that can help

**Comment by hassanfa** [comment]
Thanks. https://github.com/tiangolo/meinheld-gunicorn-flask-docker is where I took the idea as well 👍🏽
