### ISSUE TITLE
Bug, following qc overtime for microbial throws a server error

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/vogue#207]
reproduce: Select microbial, and then select any other tab other than qc_over_time. Then select qc_overtime. The following error happens:
![image](https://user-images.githubusercontent.com/1086877/105963342-315a9600-6081-11eb-89d2-b64b6988d75d.png)

**Comment by mayabrandi** [comment]
I intend to work with vogue issues this week

**Comment by hassanfa** [comment]
I was looking at this as well :-) I'll leave frontend to you.

**Comment by mayabrandi** [comment]
solved by this pr https://github.com/Clinical-Genomics/vogue/pull/213
