### ISSUE TITLE
MultiQC_clarity

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/vogue#209]
MultiQC_clarity looks interesting to pull LIMS information in a more structured way: https://github.com/MultiQC/MultiQC_Clarity

@mayabrandi  have you seen this? I have not used it, but it seems promising.

**Comment by mayabrandi** [comment]
No didn’t see that. Cool!

**Comment by hassanfa** [comment]
LIMS will be decoupled from Vogue. See the other issues. I don't think we can use this in Vogue.
