### ISSUE TITLE
Microbial QC over time - feature requests

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/vogue#219]
The micro QC-over time plot is currently looks like this:
![Skärmavbild 2021-02-02 kl  13 06 11](https://user-images.githubusercontent.com/1306333/106598073-8a319f00-6557-11eb-9318-c690776edac8.png)

And you can choose qc metric in the drop down menue:
![Skärmavbild 2021-02-02 kl  13 06 15](https://user-images.githubusercontent.com/1306333/106598082-8dc52600-6557-11eb-800f-256867d3dc37.png)

- [x] We want dodt plots with hoover functionality to be able to spot outliers.
- [x] box with outlyers

We want to be able to filter on different parameters such as:

- [ ] average qc - grouped by lot nummer  (fins inte ännu)
- [ ] average qc - grouped by dna-extraction-method 
- [ ] average qc - grouped by prep-kit (fins inte ännu)

- [x] Add epp in prep step to save prep method to sample udf "Prep Method"

**Comment by hassanfa** [comment]
@mayabrandi could you please provide a bit context 😂

**Comment by mayabrandi** [comment]
Pleas contribute with details in the description of this issue @annaengstrom

**Comment by mayabrandi** [comment]
> @mayabrandi could you please provide a bit context 😂

:P

**Comment by annaengstrom** [comment]
For information, we do not use one specific lot number for one prep, there are several. How would you imagine to show this?
