### ISSUE TITLE
Make the current version of the code up and running

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/vogue#22]
We have a url: https://vogue.scilifelab.se/
Need to set up the database at some server and get the front end code running so that people can look at it.

**Comment by ingkebil** [comment]
Let's split this up in two issues:
- setting up the vogue-stage mongodb
- setting up vogue-stage website

**Comment by mayabrandi** [comment]
Let me know when we kan work on this together! @ingkebil
