### ISSUE TITLE
Separate covid data from microbial data in alla plots

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/vogue#221]
For this to happen we need a covid apptag and/or a separate covid application category.

**Comment by annaengstrom** [comment]
"cov" has been decided to be used as category. /ALY - VW

Apptag will be decided [here](https://github.com/Clinical-Genomics/cgp-sars-cov-2-sequencing/issues/1).

**Comment by mayabrandi** [comment]
perfect. There are no changes needed in vogue for this. What is needed is just that the new apptags with the correct prep-category are set in cg. That should be handeled in this [issue](https://github.com/Clinical-Genomics/cgp-sars-cov-2-sequencing/issues/1 )
Ill close this card.
