### ISSUE TITLE
Discuss release models for vogue

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/vogue#224]
Pretty much title.

Current release model for Vogue is similar to Scout.

@mayabrandi What changes would you like to discuss?

**Comment by mayabrandi** [comment]
After using this release model a while I felt maybe it’d be easier using bump version after all.

**Comment by hassanfa** [comment]
I highly recommend bumpversion. Makes tagging and releases much easier. Do you want to take this on Maya or should I?

**Comment by mayabrandi** [comment]
Please do it if you have time and ill review

**Comment by hassanfa** [comment]
Changed title to Vogue only. For cg-lims and limsmock please refer in their repository.
