### ISSUE TITLE
MUTANT QC metrics

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/vogue#238]
1. Path for QC files here `/home/proj/production/mutant/cases/*/*.json`: `/home/proj/production/mutant/cases/*/results/ticketid_20210412.json`
2. Add these either as new dict similar to MicroSalt or make one of its own
3. No MultiQC for now

**Comment by hassanfa** [comment]
related to https://github.com/Clinical-Genomics/cgp-sars-cov-2-sequencing/issues/27

I'll update this one and add more details later on.

**Comment by Mropat** [comment]
duplicate of #273
