### ISSUE TITLE
Negative values for turnaround times for year 2021 - bug?

### ISSUE THREAD

**Issue by annaengstrom** [Clinical-Genomics/vogue#246]
**What:**
There are negative values for turnaround times for year 2021. This is probably not correct?

Also, values seems to differ between April and May for **Time from sequenced to delivered** *grouped by category* and *grouped by priority*.

**Where:**
Preps > Turnaround times > year 2021

**Example plots from year 2021:**
![Screenshot 2021-06-03 at 12 08 14](https://user-images.githubusercontent.com/36469416/120628090-9590ca80-c464-11eb-9479-0d4f52212ff0.png)
![Screenshot 2021-06-03 at 12 08 04](https://user-images.githubusercontent.com/36469416/120628093-96296100-c464-11eb-9897-5f3d492c8269.png)
![Screenshot 2021-06-03 at 12 07 40](https://user-images.githubusercontent.com/36469416/120628096-96c1f780-c464-11eb-93f9-4aa717aabb3b.png)
![Screenshot 2021-06-03 at 12 07 32](https://user-images.githubusercontent.com/36469416/120628101-975a8e00-c464-11eb-8d0f-dee0484d4502.png)

**Comment by mayabrandi** [comment]
Kollat lite på detta och orsaken till negativa värden beror i regel på att receptioncontol körts om efter delivery. Preventivt kan vi lägga in en check så att det inte händer på prov iu framtiden. Får kanske ta och gå igenom alla gamla prov med fel värden och rätta till dom.

**Comment by annaengstrom** [comment]
Att de har körts om (reception control) beror kanske på att kunden har skickat mer prov, det vill vi kunna göra.

**Comment by mayabrandi** [comment]
[This](https://github.com/Clinical-Genomics/cg_lims/pull/111) pr wich is deployed on production makes negative dates imposible. However we still need to adjust old dates.
