### ISSUE TITLE
No data for 2022 available

### ISSUE THREAD

**Issue by annaengstrom** [Clinical-Genomics/vogue#278]
**What:**
There is no data for year 2022, please add this.

**Where:**
In all places on the website.

**Other comments:**

**Comment by mayabrandi** [comment]
Okej so the reason for this is a huge mystery. Running master v3.5.0 (same as was deployed on production) locally showed data for 2022. I made a pr fixing  a release  bug for vogue-stage. (totally unrelated to the current issue) But when deployung the new release the 2022-bug was myseriously fixed @Mropat can confirm that there must have been a goast involved in this mystery :) Anyway. Data is there now. Closing issue.
