### ISSUE TITLE
No Balsamic plots since june 2021

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/vogue#283]
**What:**
Add Balsamic plots to Vogue

**Where:**

**Other comments:**
The data from 2021 might have been added manually by Hassan

**Comment by Mropat** [comment]
Balsamic was removed from list of pipelines to upload to vogue, ever since Balsamic stopped producing a qcmetrics file compatible with upload to Vogue. The author and responsible for this upload and trending no longer works on Vogue and the fix to this is not planned in the near future
