### ISSUE TITLE
Change Flask_oauth for Flask-Dance

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/vogue#31]
**Problem**
https://github.com/mitsuhiko/flask-oauth

The project has been abandoned.

**Describe the solution you'd like**
Move out the Flask-oauth code in favour of Flask-Dance: https://github.com/singingwolfboy/flask-dance

**Comment by mayabrandi** [comment]
Flask-oauth was never used. Only imported. The import has been removed!

**Comment by hassanfa** [comment]
This is done @mayabrandi , right?

**Comment by moonso** [comment]
Yes it is not a dependency anymore: https://github.com/Clinical-Genomics/vogue/blob/master/requirements.txt
