### ISSUE TITLE
Set up coveralls

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/vogue#33]
**Who: Does your feature request involves multiple parties?**
Target audience are the developers of vogue.

**Problem**
Vogue has no automatic coverage calculation. Having this would enable the project to enforce small incremental increases in test coverage.

**Describe the solution you'd like**
Coveralls can be found here: https://coveralls.io/ .
Coveralls needs to be run as a last step in our continuous integration TravisCI. TravisCI has been configured with a `.travis.yml` config file. On tips on how to enable coveralls, please have a look at other config files at CG, e.g. https://github.com/Clinical-Genomics/cg/blob/master/.travis.yml

- [ ] Enable coveralls so it runs with TravisCI on the coveralls website
- [ ] Add a coveralls badge to the main README of this project
- [ ] Add coveralls as a 'status check' for the protected branch 'master' on github (settings -> branches -> master -> status check)
- [ ] Set "Coverage Threshold for failure" to current coverage, set "Coverage Decrease Threshold for failure" to "0.1%" on coveralls (login into coveralls, go to vogue -> settings)

**Comment by hassanfa** [comment]
This is done.
