### ISSUE TITLE
Move load samples out of vogue and into CG

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/vogue#34]
**Who: Does your feature request involves multiple parties?**

**Problem**
Currently, vogue is connecting directly to LIMS. No application at CG should connect directly to LIMS and all traffic should be going through the `cg` package.

**Describe the solution you'd like**
CG will query LIMS and provide the information needed through a CLI.
Vogue will have to have a CLI that accepts the output created by the `cg` CLI.
The two CLI's need to communicate with one another at regular intervals which can be achieved through a crontab entry.

What still needs to be done during planning:
- discuss on how both CLI's need to look like
- describe `cg` CLI in an cg issue
- discuss data format of `cg` CLI output

**Comment by hassanfa** [comment]
Closing for now,

**Comment by mayabrandi** [comment]
This is actually WIP.

**Comment by hassanfa** [comment]
My bad. It was an ancient issue, and I thought it is stale. If text body is still relevant, lets open it then.

**Comment by mayabrandi** [comment]
Started working on it last week :)

**Comment by hassanfa** [comment]
We should start again without Vogue meetings. Meeting notes were good way of tracking it. But it is outside scope of this issue. I'll DM you on Slack ;-)
