### ISSUE TITLE
Bonemarrow -> Bone marrow

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/vogue#73]
**What:**
Bonemarrow -> Bone marrow

**Where:**
In the legend for target enrichment

**Other comments:**

**Comment by mayabrandi** [comment]
Not sure how to handle this one. All the groups in a plot are defined by the "source" udf on a sample in LIMS. If it has the value bonemarrow that is what the group will be called. I could have some translation dictionary in the constants/constants.py. But then it also need to be maintained when new sources are used..

**Comment by henrikstranneheim** [comment]
It is always best to change at the source and then all downstream processes do not have to bother and sync. However, if this is hard to accomplish LIMS, let it be for now in Vogue and consider if it is worth fixing in LIMS. We can discuss it on Monday.

**Comment by hassanfa** [comment]
@henrikstranneheim Is this still relevant?

**Comment by henrikstranneheim** [comment]
No, I think it would be best to handle at the source instead.
